// pptxresult.js - Display and Download Generated Presentation

document.addEventListener('DOMContentLoaded', () => {
  const slidesContainer = document.getElementById('slidesContainer');
  const downloadBtn = document.getElementById('downloadBtn');
  const editBtn = document.getElementById('editBtn');
  const toast = document.getElementById('toast');

  let presentationData = null;

  // Show toast notification
  function showToast(message, isError = false) {
    if (!toast) return;
    toast.textContent = message;
    toast.classList.remove('hidden');
    toast.style.background = isError ? '#dc2626' : 'var(--accent)';
    setTimeout(() => toast.classList.add('hidden'), 3000);
  }

  // Display slides in the container
  function displaySlides(slides) {
    if (!slidesContainer) return;
    
    slidesContainer.innerHTML = '';
    
    slides.forEach((slide, index) => {
      const slideCard = document.createElement('div');
      slideCard.className = 'slide-card';
      slideCard.style.animationDelay = `${index * 0.1}s`;
      
      // Add slide number indicator
      const slideNumber = document.createElement('div');
      slideNumber.className = 'slide-number';
      slideNumber.textContent = `${index + 1}/${slides.length}`;
      
      // Image section
      const image = document.createElement('img');
      image.className = 'slide-image';
      image.src = slide.imageUrl;
      image.alt = slide.title;
      image.loading = 'lazy';
      image.onerror = () => {
        // Fallback if image fails to load
        image.src = 'https://picsum.photos/800/400?random=' + index;
      };
      
      // Content section
      const contentDiv = document.createElement('div');
      contentDiv.className = 'slide-content';
      
      const title = document.createElement('h2');
      title.className = 'slide-title';
      title.textContent = slide.title;
      
      const bulletsList = document.createElement('ul');
      bulletsList.className = 'slide-bullets';
      
      if (slide.bullets && Array.isArray(slide.bullets)) {
        slide.bullets.forEach(bullet => {
          const li = document.createElement('li');
          li.textContent = bullet;
          bulletsList.appendChild(li);
        });
      }
      
      contentDiv.appendChild(title);
      contentDiv.appendChild(bulletsList);
      
      slideCard.appendChild(slideNumber);
      slideCard.appendChild(image);
      slideCard.appendChild(contentDiv);
      
      slidesContainer.appendChild(slideCard);
    });
  }

  // Download as PowerPoint using PptxGenJS
  async function downloadPresentation() {
    if (!presentationData || !presentationData.slides || presentationData.slides.length === 0) {
      showToast('No presentation data found', true);
      return;
    }

    if (typeof PptxGenJS === 'undefined') {
      showToast('PPTX library not loaded', true);
      return;
    }

    // Show loading state on button
    const originalText = downloadBtn.innerHTML;
    downloadBtn.innerHTML = '<span class="spinner" style="display:inline-block;"></span> Generating...';
    downloadBtn.disabled = true;

    try {
      const PptxGenJS = window.PptxGenJS;
      const pptx = new PptxGenJS();
      
      // Set presentation properties
      pptx.defineLayout({ name: 'WIDE', width: 10, height: 5.625 }); // 16:9 aspect ratio
      pptx.layout = 'WIDE';
      
      // Add title slide
      const titleSlide = pptx.addSlide();
      titleSlide.addText(presentationData.topic || 'AI Generated Presentation', {
        x: 0.5, y: 2, w: 9, h: 1.5,
        fontSize: 36, bold: true, color: '00695c', align: 'center'
      });
      titleSlide.addText(`Style: ${presentationData.style || 'Professional'}`, {
        x: 0.5, y: 3.5, w: 9, h: 0.5,
        fontSize: 16, color: '666666', align: 'center'
      });
      titleSlide.addText(`Generated by rehab.ai on ${new Date(presentationData.generatedAt).toLocaleDateString()}`, {
        x: 0.5, y: 5, w: 9, h: 0.4,
        fontSize: 10, color: '999999', align: 'center'
      });
      
      // Add content slides
      for (let i = 0; i < presentationData.slides.length; i++) {
        const slide = presentationData.slides[i];
        const pptxSlide = pptx.addSlide();
        
        // Add title
        pptxSlide.addText(slide.title, {
          x: 0.5, y: 0.3, w: 9, h: 0.8,
          fontSize: 28, bold: true, color: '00695c'
        });
        
        // Add bullets
        let bulletText = '';
        if (slide.bullets && Array.isArray(slide.bullets)) {
          bulletText = slide.bullets.map(b => '• ' + b).join('\n');
        }
        
        if (bulletText) {
          pptxSlide.addText(bulletText, {
            x: 0.5, y: 1.2, w: 5.5, h: 3.5,
            fontSize: 14, bullet: true, color: '333333'
          });
        }
        
        // Add image if available
        if (slide.imageUrl && slide.imageUrl !== 'https://picsum.photos/800/400?random=' + i) {
          try {
            // Fetch image and convert to base64 for embedding
            const response = await fetch(slide.imageUrl);
            const blob = await response.blob();
            const reader = new FileReader();
            
            const imageData = await new Promise((resolve) => {
              reader.onloadend = () => resolve(reader.result);
              reader.readAsDataURL(blob);
            });
            
            pptxSlide.addImage({
              data: imageData,
              x: 6.2, y: 1.2, w: 3.3, h: 2.5,
              sizing: { type: 'contain', w: 3.3, h: 2.5 }
            });
          } catch (err) {
            console.warn('Could not embed image:', slide.imageUrl);
          }
        }
        
        // Add slide number
        pptxSlide.addText(`${i + 1}/${presentationData.slides.length}`, {
          x: 9, y: 5.3, w: 0.5, h: 0.3,
          fontSize: 8, color: '999999', align: 'right'
        });
      }
      
      // Save the presentation
      const fileName = `${presentationData.topic.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_presentation.pptx`;
      await pptx.writeFile({ fileName });
      
      showToast('Presentation downloaded successfully!');
      
    } catch (error) {
      console.error('Download error:', error);
      showToast('Failed to generate PowerPoint: ' + error.message, true);
    } finally {
      downloadBtn.innerHTML = originalText;
      downloadBtn.disabled = false;
    }
  }

  // Load presentation data from sessionStorage
  function loadPresentationData() {
    const storedData = sessionStorage.getItem('presentationData');
    
    if (!storedData) {
      // Show empty state
      slidesContainer.innerHTML = `
        <div class="empty-state">
          <div class="empty-icon">📊</div>
          <h3>No Presentation Found</h3>
          <p>You haven't generated any presentation yet.</p>
          <button class="create-btn" onclick="window.location.href='presentation.html'">Create New Presentation</button>
        </div>
      `;
      return false;
    }
    
    try {
      presentationData = JSON.parse(storedData);
      
      if (!presentationData.slides || presentationData.slides.length === 0) {
        throw new Error('No slides in presentation data');
      }
      
      displaySlides(presentationData.slides);
      return true;
    } catch (error) {
      console.error('Parse error:', error);
      slidesContainer.innerHTML = `
        <div class="empty-state">
          <div class="empty-icon">⚠️</div>
          <h3>Invalid Presentation Data</h3>
          <p>There was an error loading your presentation.</p>
          <button class="create-btn" onclick="window.location.href='presentation.html'">Create New Presentation</button>
        </div>
      `;
      return false;
    }
  }

  // Edit button handler - go back to presentation maker
  function editPresentation() {
    window.location.href = 'presentation.html';
  }

  // Event listeners
  if (downloadBtn) {
    downloadBtn.addEventListener('click', downloadPresentation);
  }
  
  if (editBtn) {
    editBtn.addEventListener('click', editPresentation);
  }
  
  // Load data on page load
  loadPresentationData();
  
  // Add keyboard shortcut for download (Ctrl+S)
  document.addEventListener('keydown', (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 's') {
      e.preventDefault();
      if (downloadBtn && !downloadBtn.disabled) {
        downloadPresentation();
      }
    }
  });
});